name: Mise à jour des données météorologiques

on:
  schedule:
    - cron: '*/5 * * * *' # Exécuter toutes les heures

jobs:
  update_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v2

    - name: Exécution du script Python
      run: python update_forecast.py

    - name: Commit et pousser les modifications
      run: |
        git config user.email "rivaldi.tristan@orange.fr"
        git config user.name "TristanRivaldi"
        git add .
        git commit -m 'Mise à jour des données météorologiques'
        git push
      env:
        TOKEN: ${{ secrets.TOKEN }}
