name: Update Weather Data

on:
  schedule:
    - cron: "0 * * * *"  # Exécuter tous les jours à minuit UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choisissez la version de Python que vous utilisez

    - name: Install dependencies
      run: pip install pandas requests

    - name: Run Python script to update data
      run: python update_forecast.py
