name: Update Weather Forecast

on:
  schedule:
    - cron: '30 7 * * *' # Définit l'exécution quotidienne à 7h30 chaque jour

jobs:
  update-weather-forecast:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code source
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install les dépendances
        run: |
          pip install pandas requests

      - name: Configure Git with Personal Access Token
        run: |
          git config --global user.email "rivaldi.tristan@orange.fr"
          git config --global user.name "TristanRivaldi"
          git remote set-url origin https://github.com/TristanRivaldi/meteo
        env:
          GH_TOKEN: ${{ secrets.TOKEN }} # Utilisez le secret "TOKEN" comme jeton d'accès personnel

      - name: Execute update_forecast.py
        run: |
          python update_forecast.py
