name: Update Weather Forecast

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update-forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4  # Remplacez par la version exacte de Python que vous utilisez

    - name: Install requests and pandas modules
      run: |
        python -m pip install requests
        python -m pip install pandas

    - name: Run update_forecast.py
      run: python update_forecast.py

