name: Update Weather Data

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install pandas requests

    - name: Configure Git
      run: |
        git config --global user.email "rivaldi.tristan@orange.fr"
        git config --global user.name "TristanRivaldi"

    - name: Run Python script to update data
      run: python update_forecast.py je veux supprimer la partie sur les token
