name: Update Weather Data

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install pandas requests

    - name: Configure Git
      run: |
        git config --global user.email "votre-email@example.com"
        git config --global user.name "Votre Nom"

    - name: Run Python script to update data
      run: python update_forecast.py
