name: Update Forecast
on:
  schedule:
    - cron: '*/5 * * * *'  # Exécutez toutes les 5 minutes

jobs:
  update_forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Configure Git
      run: |
        git config --global user.email "rivaldi.tristan@orange.fr"
        git config --global user.name "TristanRivaldi"

    - name: Exécutez le script update_forecast.py
      run: |
        python update_forecast.py

