name: Update Weather Forecast

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  update-forecast:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Assurez-vous de spécifier la version de Python que vous utilisez

    - name: Run update_forecast.py
      run: python update_forecast.py
